const AVATAR_URLS = [
  "https://robohash.org/random-seed",
  "https://robohash.org/nsd",
  "https://robohash.org/nsddf",
  "https://robohash.org/nsdfdsm",
  "https://robohash.org/nsdkjfds",
  "https://robohash.org/extra1",
  "https://robohash.org/extra2",
  "https://robohash.org/extra3",
];

export const dummyEvents = [
  {
    id: 1,
    title: "Taylor Swift Tribute Concert",
    date: "16 Nov",
    duration: "2.5 hours",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
    hostName: "Jennifer Dane",
    hostImage: AVATAR_URLS[0],
    category: "Concerts",
    attendees: AVATAR_URLS.slice(1, 5),
  },
  {
    id: 2,
    title: "Premier League Live Screening",
    date: "17 Nov",
    duration: "2 hours",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1459865264687-595d652de67e",
    hostName: "Mike Roberts",
    hostImage: AVATAR_URLS[1],
    category: "Sports",
    attendees: AVATAR_URLS.slice(2, 4),
  },
  {
    id: 3,
    title: "Romeo & Juliet - Modern Adaptation",
    date: "17 Nov",
    duration: "2.5 hours",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf",
    hostName: "Sarah Chen",
    hostImage: AVATAR_URLS[2],
    category: "Theatre",
    attendees: AVATAR_URLS.slice(0, 4),
  },
  {
    id: 4,
    title: "Stand-up Comedy Night",
    date: "18 Nov",
    duration: "1.5 hours",
    price: 25.99,
    image: "https://images.unsplash.com/photo-1513759565286-20e9c5fad06b",
    hostName: "Alex Thompson",
    hostImage: AVATAR_URLS[3],
    category: "Comedy",
    attendees: AVATAR_URLS.slice(1, 3),
  },
  {
    id: 5,
    title: "Winter Music Festival",
    date: "18 Nov",
    duration: "8 hours",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3",
    hostName: "Emma Wilson",
    hostImage: AVATAR_URLS[4],
    category: "Festivals",
    attendees: AVATAR_URLS,
  },
  {
    id: 6,
    title: "Digital Marketing Workshop",
    date: "19 Nov",
    duration: "3 hours",
    price: 149.99,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978",
    hostName: "David Chen",
    hostImage: AVATAR_URLS[2],
    category: "Workshops",
    attendees: AVATAR_URLS.slice(1, 6),
  },
  {
    id: 7,
    title: "International Food Festival",
    date: "19 Nov",
    duration: "4 hours",
    price: 35.99,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
    hostName: "Maria Garcia",
    hostImage: AVATAR_URLS[5],
    category: "Food",
    attendees: AVATAR_URLS.slice(2, 5),
  },
  {
    id: 8,
    title: "AI & Future of Tech Conference",
    date: "20 Nov",
    duration: "6 hours",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e",
    hostName: "Steve Jobs",
    hostImage: AVATAR_URLS[6],
    category: "Tech",
    attendees: AVATAR_URLS.slice(0, 4),
  },
  {
    id: 9,
    title: "Independent Film Screening",
    date: "20 Nov",
    duration: "2 hours",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba",
    hostName: "Christopher Nolan",
    hostImage: AVATAR_URLS[7],
    category: "Film",
    attendees: AVATAR_URLS.slice(1, 6),
  },
  {
    id: 10,
    title: "Modern Art Exhibition",
    date: "21 Nov",
    duration: "3 hours",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1531913764164-f85c52201e8c",
    hostName: "Lisa Art",
    hostImage: AVATAR_URLS[3],
    category: "Art",
    attendees: AVATAR_URLS.slice(2, 5),
  },
  {
    id: 11,
    title: "Latin Dance Workshop",
    date: "21 Nov",
    duration: "2 hours",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4",
    hostName: "Carlos Rodriguez",
    hostImage: AVATAR_URLS[4],
    category: "Dance",
    attendees: AVATAR_URLS.slice(1, 4),
  },
  {
    id: 12,
    title: "Startup Networking Event",
    date: "22 Nov",
    duration: "3 hours",
    price: 0,
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b",
    hostName: "Mark Johnson",
    hostImage: AVATAR_URLS[5],
    category: "Business",
    attendees: AVATAR_URLS.slice(0, 6),
  },
  {
    id: 13,
    title: "Underground Party",
    date: "22 Nov",
    duration: "5 hours",
    price: 45.99,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7",
    hostName: "DJ Snake",
    hostImage: AVATAR_URLS[6],
    category: "Nightlife",
    attendees: AVATAR_URLS.slice(1, 5),
  },
  {
    id: 14,
    title: "Family Fun Day",
    date: "23 Nov",
    duration: "6 hours",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368",
    hostName: "Sarah Williams",
    hostImage: AVATAR_URLS[7],
    category: "Family",
    attendees: AVATAR_URLS.slice(2, 6),
  },
  {
    id: 15,
    title: "Yoga & Meditation Retreat",
    date: "23 Nov",
    duration: "4 hours",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b",
    hostName: "Emma Peace",
    hostImage: AVATAR_URLS[0],
    category: "Health",
    attendees: AVATAR_URLS.slice(1, 4),
  },
  {
    id: 16,
    title: "Programming for Beginners",
    date: "24 Nov",
    duration: "2.5 hours",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6",
    hostName: "John Code",
    hostImage: AVATAR_URLS[1],
    category: "Education",
    attendees: AVATAR_URLS.slice(0, 3),
  },
  {
    id: 17,
    title: "Charity Run for Education",
    date: "24 Nov",
    duration: "3 hours",
    price: 25.99,
    image: "https://images.unsplash.com/photo-1533963906061-c0dd09c9d725",
    hostName: "Peter Good",
    hostImage: AVATAR_URLS[2],
    category: "Charity",
    attendees: AVATAR_URLS.slice(1, 7),
  },
  {
    id: 18,
    title: "Christmas Market Opening",
    date: "25 Nov",
    duration: "8 hours",
    price: 0,
    image: "https://images.unsplash.com/photo-1512389142860-9c449e58a543",
    hostName: "Mary Christmas",
    hostImage: AVATAR_URLS[3],
    category: "Holiday",
    attendees: AVATAR_URLS.slice(0, 5),
  },
  {
    id: 19,
    title: "Secret Supper Club",
    date: "25 Nov",
    duration: "2.5 hours",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    hostName: "Chef Mystery",
    hostImage: AVATAR_URLS[4],
    category: "Pop-ups",
    attendees: AVATAR_URLS.slice(2, 6),
  },
  {
    id: 20,
    title: "Personalized Event Recommendations",
    date: "26 Nov",
    duration: "Varies",
    price: 0,
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622",
    hostName: "AI Assistant",
    hostImage: AVATAR_URLS[5],
    category: "For You",
    attendees: AVATAR_URLS.slice(1, 4),
  },
];
